network:
  version: 2
  renderer: NetworkManager
  ethernets:
    ${NETWORK_INTERFACE}:
      dhcp4: false
      dhcp6: false
      ipv6-privacy: true
      addresses:
        - ${IPADDR}
      routes:
        - to: default
          via: 192.168.1.1
      nameservers:
        addresses:
        - 2620:119:35::35 # OpenDNS ipv6 primary
        - 2620:119:53::53 # OpenDNS ipv6 secondary
        - 208.67.222.222  # OpenDNS ipv4 primary
        - 208.67.220.220  # OpenDNS ipv4 secondary
