[global]
  security     = user
  map to guest = never
  case sensitive = yes

[misc]
  path = ${SAMBA_MOUNT_PATH_misc}
  read only  = no
  guest ok   = no
  create mask    = 0777
  directory mask = 0777

[rec]
  path = ${SAMBA_MOUNT_PATH_rec}
  read only  = no
  guest ok   = no
  create mask    = 0777
  directory mask = 0777