
[tver]
  platform = "tver"
  scraper  = "selenium"

  [tver.contents.toiro]
    title  = "住人十色"
    url    = "https://tver.jp/series/srxbqmdpvs"
    [[tver.contents.toiro.plan]]
      dow    = "土"
      anchor = ""

  [tver.contents.rion]
    title  = "ライオンの隠れ家"
    url    = "https://tver.jp/series/srp6e5qh3b"
    [[tver.contents.rion.plan]]
      dow    = "金"
      anchor = ""

  [tver.contents.okura]
    title  = "オクラ～迷宮入り事件捜査～"
    url    = "https://tver.jp/series/sr3r43aoeq"
    plan   = { "火" = "" }

  [tver.contents.zenketsu]
    title  = "全領域異常解決室"
    url    = "https://tver.jp/series/srhhcup5mk"
    [[tver.contents.rion.plan]]
      dow    = "水"
      anchor = ""

  [tver.contents.monster]
    title  = "モンスター"
    url    = "https://tver.jp/series/sr6sfbw303"
    [[tver.contents.rion.plan]]
      dow    = "月"
      anchor = ""
