

name: shellscript test
on: push
jobs:
    scripts:
        if: false
        runs-on: ubuntu-latest

        strategy:
          fail-fast: false
          matrix:
            script:
            # - __apt_install.sh
            # - __install_docker.sh
            # - __pip_install.sh
            # - __install_vscode.sh
            - .test/test.sh

        steps:
          - name: chekout
            uses: actions/checkout@v4

          - name: loop
            run:  ${GITHUB_WORKSPACE}/${{ matrix.script }}


    # deploy:
    #     runs-on: ubuntu-latest

    #     strategy:
    #       fail-fast: false
    #       matrix:
    #         script:
    #         - __link_netplan.sh

    #     steps:
    #       - name: chekout
    #         uses: actions/checkout@v4

    #       - name: loop
    #         run:  ${GITHUB_WORKSPACE}/${{ matrix.script }}


    makefile:
        if: true
        runs-on: ubuntu-latest

        steps:
          - name: chekout
            uses: actions/checkout@v4

          - name: loop
            run:  make deploy